import Image from "next/image";
import Banner from "./components/HomeComponents/Banner";
import CategorySection from "./components/HomeComponents/CategorySection";
import NewsLetter from "./components/HomeComponents/NewsLetter";
import Testimonial from "./components/common/Testimonial";
import Features from "./components/HomeComponents/Features";
import Bestsellingproducts from "./components/HomeComponents/Bestsellingproducts";
import TrendingCollections from "./components/HomeComponents/TrendingCollections";
import ProductFilter from "./components/HomeComponents/ProductFilter";
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};



export default function Home() {

  return (
    <div>
      <div>
        <Banner />
      </div>
      <div>
        <CategorySection />
      </div>
       <div>
        <ProductFilter/>
      </div>
         <div>
        <TrendingCollections/>
      </div>
       <div>
        <Bestsellingproducts/>
      </div>
      <div>
        <Features/>
      </div>
      <div>
        <Testimonial/>
      </div>
      <div>
      <NewsLetter/>
      </div>
    </div>
  );
}
